### ISSUE TITLE
'.xcodeproj' file

### ISSUE THREAD

**Issue by tejasdhanuka** [LeXa777/ImageFetcher#1]
This project is missing the '.xcodeproj' file So, cannot compile the project after download. Please make sure you upload a proper project with '.xcodeproj' file for both starter and final project

**Comment by LeXa777** [comment]
@tejasdhanuka You're spot on. It was a mistake on my part, basically the .gitignore rules where ignoring these hence they were not uploaded to github. This is now fixed.
